server:
  port: 8081

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://customer-db:5432/customer_db
    username: customer_user
    password: customer_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: false