server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
        - id: customer-route
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
          filters:
            - id: vehicle-route
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicles/**

        - id: payment-route
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

        - id: document-route
          uri: lb://document-service
          predicates:
            - Path=/api/documents/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 0.0

jwt:
  secret: mySecretKey
  expiration: 86400000
