services:
  customer-db:
    image: postgres:16
    container_name: customer-db
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_pass
    ports:
      - "5433:5432"

  vehicle-db:
    image: postgres:16
    container_name: vehicle-db
    environment:
      POSTGRES_DB: vehicle_db
      POSTGRES_USER: vehicle_user
      POSTGRES_PASSWORD: vehicle_pass
    ports:
      - "5434:5432"

  document-db:
    image: postgres:16
    container_name: document-db
    environment:
      POSTGRES_DB: document_db
      POSTGRES_USER: document_user
      POSTGRES_PASSWORD: document_pass
    ports:
      - "5436:5432"

  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
    ports:
      - "5435:5432"