services:

  customer-db:
    image: postgres:16
    container_name: customer-db
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_pass

  vehicle-db:
    image: postgres:16
    container_name: vehicle-db
    environment:
      POSTGRES_DB: vehicle_db
      POSTGRES_USER: vehicle_user
      POSTGRES_PASSWORD: vehicle_pass

  customer-service:
    build: ./customer-service
    container_name: customer-service
    depends_on:
      - customer-db
    ports:
      - "8081:8081"

  vehicle-service:
    build: ./vehicle-service
    container_name: vehicle-service
    depends_on:
      - vehicle-db
    ports:
      - "8082:8082"