server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native            # "native" = lire depuis des fichiers locaux
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs