server:
  port: 8082

spring:
  application:
    name: vehicle-service

  datasource:
    url: jdbc:postgresql://vehicle-db:5432/vehicle_db
    username: vehicle_user
    password: vehicle_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: false