server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-service-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/customers/**
              filters:
                - StripPrefix=1

            - id: vehicle-service-route
              uri: http://localhost:8082
              predicates:
                - Path=/api/vehicles/**
              filters:
                - StripPrefix=1

            - id: document-service-route
              uri: http://localhost:8084
              predicates:
                - Path=/api/documents/**
              filters:
                - StripPrefix=1

            - id: payment-service-route
              uri: http://localhost:8083
              predicates:
                - Path=/api/payments/**
              filters:
                - StripPrefix=1
