apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    editable: true